# Copyright (c) 2020 ZMK Firmware Contributors
# Copyright (c) 2020 Endian Technologies AB

# SPDX-License-Identifier: MIT

name: Build and upload Hypnos

# When to run this Workflow
on:

  # Run this Workflow when files are pushed to this Branch
  push:
    branches: [ master ]

  # Also run this Workflow when a Pull Request is created or updated in this Branch
  pull_request:
    branches: [ master ]

# Steps to run for the Workflow
jobs:
  build:
    strategy:
      matrix:
        device: [pinetime]
#       device: [pinetime, p8]
    runs-on: ubuntu-latest
    name: Build and upload
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # From https://docs.zephyrproject.org/latest/getting_started/index.html      
      - name: Install depedencies
        run:  |
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev
          cmake --version
          pip3 install --user -U west
          echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
          source ~/.bashrc
          
      # From https://github.com/lupyuen/pinetime-hypnos/blob/master/README.md
      - name: Build firmware
        run:  |
          west init -l app/
          west update
          export LOGGING="off"
          cd app/
          west build -p -b ${{ matrix.device }} hypnos
          pwd ; ls -l
          cd ..
          pwd ; ls -l

#      - name: West Init
#        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
#        id: west-init
#        with:
#          args: 'init "-l app/'
#      - name: West Update
#        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
#        id: west-update
#        with:
#          args: 'update'
#      - name: West Config Zephyr Base
#        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
#        id: west-config
#        with:
#          args: 'config "--global zephyr.base-prefer configfile"'
#      - name: West Zephyr Export
#        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
#        id: west-zephyr-export
#        with:
#          args: 'zephyr-export'
#      - name: West Build ${{ matrix.device }}
#        uses: 'docker://zmkfirmware/zephyr-west-action-arm:latest'
#        id: west-build
#        with:
#          args: 'build "-p -b ${{ matrix.device }} app/hypnos"'
#      - name: Get short git hash
#        id: vars
#        shell: bash
#        run:
#          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # Upload firmware build
#      - name: Upload firmware build
#        uses: actions/upload-artifact@v2
#        with:
          # Append git hash to file name
#          name: ${{ matrix.device }}-hypnos-fw-${{ steps.vars.outputs.sha_short }}
#          path: build/zephyr/zephyr.*
